// ══════════════════════════════════════
//  CATÁLOGO DE PERFUMES
//  Para agregar uno nuevo, copia un bloque { ... } y edítalo.
//  gender acepta: "hombre" | "mujer" | "unisex"
//  stock: true = disponible, false = se muestra "Agotado" y no se puede pedir
// ══════════════════════════════════════
const PERFUMES = [
  {
    id: "valentino-born-in-roma-intense",
    name: "Valentino Uomo Born In Roma Intense",
    brand: "Valentino",
    category: "disenador",
    gender: "hombre",
    img: "assets/birintense.png",
    desc: "Sensual, elegante y adictivo. Una mezcla intensa de vainilla y lavanda que deja una estela inolvidable.",
    stock: true,
    prices: { "5ml": 40000, "10ml": 75000, "full": 620000 },
    notes: { salida: "Vainilla", corazon: "Lavanda", fondo: "Vetiver" }
  },
  {
    id: "eau-issey-pour-homme",
    name: "L'Eau d'Issey Pour Homme",
    brand: "Issey Miyake",
    category: "disenador",
    gender: "hombre",
    img: "assets/isseymiyake.png",
    desc: "Fresco, cítrico y atemporal. Un clásico masculino perfecto para el día y el clima cálido.",
    stock: true,
    prices: { "5ml": 26000, "10ml": 45000, "full": 290000 },
    notes: { salida: "Yuzu, Limón, Bergamota", corazon: "Nuez Moscada, Canela, Lirio de los Valles", fondo: "Vetiver, Cedro, Almizcle, Tabaco" }
  },
  {
    id: "khamrah-waha",
    name: "Khamrah Waha",
    brand: "Lattafa",
    category: "arabe",
    gender: "unisex",
    img: "assets/waha.png",
    desc: "Dulce, cálido y envolvente. Una interpretación exótica con vainilla, especias y un toque gourmand irresistible.",
    stock: true,
    prices: { "5ml": 25000, "10ml": 42000, "full": 250000 },
    notes: { salida: "Canela, Bergamota", corazon: "Praliné, Dátiles, Nardos", fondo: "Vainilla, Haba Tonka, Benjuí, Ámbar" }
  },
  {
    id: "212-vip-black",
    name: "212 VIP Black",
    brand: "Carolina Herrera",
    category: "disenador",
    gender: "hombre",
    img: "assets/212vipblack.png",
    desc: "Seductor, moderno y nocturno. Un perfume dulce y aromático diseñado para destacar en cualquier salida.",
    stock: true,
    prices: { "5ml": 30000, "10ml": 55000, "full": 420000 },
    notes: { salida: "Absenta, Anís, Hinojo", corazon: "Lavanda", fondo: "Vainilla Negra, Almizcle" }
  },
  {
    id: "tag-uomo-rosso",
    name: "TAG Uomo Rosso",
    brand: "Armaf",
    category: "arabe",
    gender: "hombre",
    img: "assets/TagUomoRosso.png",
    desc: "Elegante, seductor y versátil. Un aroma cálido con un toque dulce y especiado que destaca especialmente en la noche.",
    stock: true,
    prices: { "5ml": 22000, "10ml": 42000, "full": 215000 },
    notes: { salida: "Bergamota, Limón, Pimienta Rosa", corazon: "Lavanda, Geranio, Canela", fondo: "Ámbar, Vainilla, Cedro, Pachulí" }
  },
  {
    id: "amethyst",
    name: "Amethyst",
    brand: "Lattafa",
    category: "arabe",
    gender: "mujer",
    img: "assets/Amethyst.png",
    desc: "Elegante, floral y oscuro. Una rosa intensa con un toque de oud que transmite lujo y sofisticación.",
    stock: true,
    prices: { "5ml": 20000, "10ml": 35000, "full": 200000 },
    notes: { salida: "Rosa, Pimienta Rosa", corazon: "Jazmín, Rosa Búlgara", fondo: "Oud, Ámbar, Vainilla" }
  },
  {
    id: "dynasty",
    name: "Dynasty",
    brand: "Lattafa",
    category: "arabe",
    gender: "hombre",
    img: "assets/Dynasty.png",
    desc: "Moderno, elegante y versátil. Un aroma fresco con un fondo amaderado que funciona en cualquier ocasión.",
    stock: true,
    prices: { "5ml": 23000, "10ml": 42000, "full": 230000 },
    notes: { salida: "Bergamota, Mandarina", corazon: "Lavanda, Geranio", fondo: "Vetiver, Cedro, Ámbar" }
  },
  {
    id: "hawas-verde",
    name: "Hawas Verde",
    brand: "Rasasi",
    category: "arabe",
    gender: "hombre",
    img: "assets/HawasVerde.png",
    desc: "Fresco, verde y extremadamente limpio. Perfecto para clima cálido y uso diario.",
    stock: true,
    prices: { "5ml": 30000, "10ml": 55000, "full": 320000 },
    notes: { salida: "Bergamota, Toronja", corazon: "Jengibre, Cedro", fondo: "Sándalo, Almizcle, Ámbar" }
  },
  {
    id: "yara",
    name: "Yara",
    brand: "Lattafa",
    category: "arabe",
    gender: "mujer",
    img: "assets/YaraPink.png",
    desc: "Dulce, cremoso y femenino. Una fragancia irresistible con vainilla y frutas tropicales.",
    stock: true,
    prices: { "5ml": 20000, "10ml": 35000, "full": 210000 },
    notes: { salida: "Heliotropo, Orquídea, Mandarina", corazon: "Frutas Tropicales", fondo: "Vainilla, Sándalo, Almizcle" }
  },
  {
    id: "9am-pour-femme",
    name: "9AM Pour Femme EDP",
    brand: "Afnan",
    category: "arabe",
    gender: "mujer",
    img: "assets/9AMPourFemme.png",
    desc: "Luminoso, floral y elegante. Una fragancia femenina fresca con excelente duración.",
    stock: true,
    prices: { "5ml": 22000, "10ml": 42000, "full": 225000 },
    notes: { salida: "Mandarina, Bergamota, Toronja", corazon: "Rosa, Jazmín, Grosella Negra", fondo: "Almizcle, Vainilla, Cedro" }
  },
  {
    id: "bright-crystal",
    name: "Bright Crystal",
    brand: "Versace",
    category: "disenador",
    gender: "mujer",
    img: "assets/BrightCrystal.png",
    desc: "Fresco, floral y delicado. Un clásico femenino elegante y muy fácil de llevar.",
    stock: true,
    prices: { "5ml": 30000, "10ml": 55000, "full": 340000 },
    notes: { salida: "Yuzu, Granada", corazon: "Peonía, Magnolia, Flor de Loto", fondo: "Almizcle, Caoba, Ámbar" }
  },
  {
    id: "arabians-tonka",
    name: "Arabians Tonka",
    brand: "Montale",
    category: "nicho",
    gender: "hombre",
    img: "assets/ArabiansTonka.png",
    desc: "Potente, dulce y lujoso. Una mezcla intensa de oud, rosa y haba tonka con una duración espectacular.",
    stock: true,
    prices: { "5ml": 37000, "10ml": 65000, "full": 520000 },
    notes: { salida: "Azafrán, Bergamota", corazon: "Rosa de Bulgaria, Oud", fondo: "Haba Tonka, Ámbar, Almizcle, Azúcar de Caña" }
  },
  {
    id: "eros-edp",
    name: "Eros EDP",
    brand: "Versace",
    category: "disenador",
    gender: "hombre",
    img: "assets/erosedp.png",
    desc: "Seductor, intenso y adictivo. Una fragancia dulce y potente que deja huella en cualquier ambiente.",
    stock: true,
    prices: { "5ml": 26000, "10ml": 45000, "full": 290000 },
    notes: { salida: "Menta, Manzana, Limón", corazon: "Haba Tonka, Ambroxan, Geranio", fondo: "Vainilla, Cedro, Vetiver" }
  },
  {
    id: "bois-imperial",
    name: "Bois Imperial",
    brand: "Essential Parfums",
    category: "nicho",
    gender: "unisex",
    img: "assets/boisimperial.png",
    desc: "Nicho, elegante y moderno. Un aroma amaderado fresco con un aire limpio y sofisticado que no pasa desapercibido.",
    stock: false,
    prices: { "5ml": 40000, "10ml": 75000, "full": 560000 },
    notes: { salida: "Albahaca, Pimienta", corazon: "Vetiver, Akigalawood", fondo: "Maderas, Pachulí" }
  },
  {
    id: "vulcan-feu",
    name: "Vulcan Feu",
    brand: "French Avenue",
    category: "arabe",
    gender: "hombre",
    img: "assets/vulcanfeu.png",
    desc: "Caliente, especiado y explosivo. Una fragancia intensa con vibra ardiente perfecta para la noche.",
    stock: true,
    prices: { "5ml": 24000, "10ml": 44000, "full": 280000 },
    notes: { salida: "Canela, Pimienta", corazon: "Tabaco, Incienso", fondo: "Ámbar, Vainilla, Maderas" }
  },
  {
    id: "hawas-kobra",
    name: "Hawas Kobra",
    brand: "Rasasi",
    category: "arabe",
    gender: "hombre",
    img: "assets/hawaskobra.png",
    desc: "Más oscuro y atrevido. Una versión intensa con un toque dulce y misterioso ideal para destacar.",
    stock: true,
    prices: { "5ml": 24000, "10ml": 44000, "full": 265000 },
    notes: { salida: "Frutas, Cítricos", corazon: "Especias, Lavanda", fondo: "Ámbar, Maderas, Almizcle" }
  },
  {
    id: "hawas-ice",
    name: "Hawas Ice",
    brand: "Rasasi",
    category: "arabe",
    gender: "hombre",
    img: "assets/hawasIce.png",
    desc: "Ultra fresco y vibrante. Una fragancia limpia, acuática y moderna perfecta para clima caliente.",
    stock: true,
    prices: { "5ml": 24000, "10ml": 44000, "full": 275000 },
    notes: { salida: "Cítricos, Manzana", corazon: "Notas acuáticas, Lavanda", fondo: "Almizcle, Maderas" }
  },
  {
    id: "asad-elixir",
    name: "Asad Elixir",
    brand: "Lattafa",
    category: "arabe",
    gender: "hombre",
    img: "assets/asadelixir.png",
    desc: "Intenso, dulce y especiado. Una fragancia envolvente con mucha personalidad y excelente duración.",
    stock: true,
    prices: { "5ml": 23000, "10ml": 43000, "full": 230000 },
    notes: { salida: "Pimienta, Canela", corazon: "Vainilla, Incienso", fondo: "Ámbar, Maderas, Benjuí" }
  },
  {
    id: "precieux",
    name: "Precieux",
    brand: "Lattafa",
    category: "arabe",
    gender: "unisex",
    img: "assets/Precieux.png",
    desc: "Elegancia pura y sofisticación. Una fragancia amaderada y ambarada que proyecta lujo en cada spray.",
    stock: true,
    prices: { "5ml": 32000, "10ml": 59000, "full": 320000 },
    notes: { salida: "Azafrán, Bergamota", corazon: "Rosa, Jazmín, Madera de Cedro", fondo: "Ámbar, Almizcle, Vainilla" }
  },
  {
    id: "9pm-night-out",
    name: "9PM Night Out",
    brand: "Afnan",
    category: "arabe",
    gender: "hombre",
    img: "assets/9pmNightOut.png",
    desc: "La evolución del 9PM original. Más intenso, nocturno y perfecto para eventos especiales.",
    stock: true,
    prices: { "5ml": 25000, "10ml": 45000, "full": 290000 },
    notes: { salida: "Manzana, Canela, Bergamota", corazon: "Flor de Azahar, Lirio de los Valles", fondo: "Vainilla, Haba Tonka, Ámbar" }
  },
  {
    id: "hawas-for-him",
    name: "Hawas for Him",
    brand: "Rasasi",
    category: "arabe",
    gender: "hombre",
    img: "assets/HawasForHim.png",
    desc: "El rey de la seducción acuática. Frescura marina combinada con notas frutales y un fondo amaderado irresistible.",
    stock: true,
    prices: { "5ml": 22000, "10ml": 42000, "full": 240000 },
    notes: { salida: "Manzana, Bergamota, Canela", corazon: "Notas Marinas, Ciruela, Cardamomo", fondo: "Ámbar Gris, Almizcle, Madera a la deriva" }
  },
  {
    id: "his-confession",
    name: "His Confession",
    brand: "Lattafa",
    category: "arabe",
    gender: "hombre",
    img: "assets/HisConfession.png",
    desc: "Inspirado en la intensidad y la elegancia. Un aroma profundo, especiado y magnético.",
    stock: false,
    prices: { "5ml": 21000, "10ml": 40000, "full": 245000 },
    notes: { salida: "Canela, Mandarina", corazon: "Lavanda, Especias", fondo: "Vainilla, Pachulí" }
  },
  {
    id: "le-male",
    name: "Le Male",
    brand: "Jean Paul Gaultier",
    category: "disenador",
    gender: "hombre",
    img: "assets/LeMaleJPG.png",
    desc: "Un clásico atemporal. Frescura de lavanda combinada con la calidez de la vainilla.",
    stock: true,
    prices: { "5ml": 35000, "10ml": 65000, "full": 610000 },
    notes: { salida: "Menta, Lavanda", corazon: "Flor de azahar, Canela", fondo: "Vainilla, Haba tonka" }
  },
  {
    id: "le-beau-le-parfum",
    name: "Le Beau Le Parfum",
    brand: "Jean Paul Gaultier",
    category: "disenador",
    gender: "hombre",
    img: "assets/LeBeauLeParfum.png",
    desc: "Cálido, amaderado y magnético. Una versión más intensa y sensual del icónico Le Beau, con un fondo dulce y envolvente.",
    stock: true,
    prices: { "5ml": 35000, "10ml": 65000, "full": 610000 },
    notes: { salida: "Cardamomo, Toronja", corazon: "Madera de Coco, Salvia", fondo: "Haba Tonka, Amberwood" }
  },
  {
    id: "le-male-elixir",
    name: "Le Male Elixir",
    brand: "Jean Paul Gaultier",
    category: "disenador",
    gender: "hombre",
    img: "assets/LeMaleElixir.png",
    desc: "La versión más oscura y concentrada de Le Male. Intenso, ambarado y con una estela que dura todo el día.",
    stock: true,
    prices: { "5ml": 35000, "10ml": 65000, "full": 610000 },
    notes: { salida: "Lavanda", corazon: "Vainilla Absoluta", fondo: "Haba Tonka, Cedro, Madera de Gaiac" }
  },
  {
    id: "stallion-53",
    name: "Stallion 53",
    brand: "Emper",
    category: "arabe",
    gender: "hombre",
    img: "assets/stallion53.png",
    desc: "Potente, masculino y elegante. Una fragancia intensa con carácter fuerte que impone presencia desde el primer momento.",
    stock: true,
    prices: { "5ml": 21000, "10ml": 41000, "full": 210000 },
    notes: { salida: "Bergamota, Pimienta", corazon: "Lavanda, Geranio", fondo: "Ámbar, Madera, Almizcle" }
  },
  {
    id: "amber-oud-gold-edition",
    name: "Amber Oud Gold Edition",
    brand: "Al Haramain",
    category: "arabe",
    gender: "unisex",
    img: "assets/AmberOudGoldEdition.png",
    desc: "Lujo puro. Una fragancia dulce, frutal y ambarada con una proyección inigualable.",
    stock: true,
    prices: { "5ml": 23000, "10ml": 43000, "full": 295000 },
    notes: { salida: "Notas verdes, Bergamota", corazon: "Melón, Piña, Ámbar", fondo: "Vainilla, Almizcle" }
  },
  {
    id: "odyssey-aqua",
    name: "Odyssey Aqua",
    brand: "Armaf",
    category: "arabe",
    gender: "hombre",
    img: "assets/OdysseyAqua.png",
    desc: "Acuático, fresco y afrutado. Perfecto para el día a día y climas cálidos.",
    stock: true,
    prices: { "5ml": 23000, "10ml": 42000, "full": 230000 },
    notes: { salida: "Naranja, Toronja", corazon: "Menta, Notas acuáticas", fondo: "Ambroxan, Maderas" }
  },
  {
    id: "9pm",
    name: "9PM",
    brand: "Afnan",
    category: "arabe",
    gender: "hombre",
    img: "assets/9Pm.png",
    desc: "Dulce, nocturno y seductor. Una bomba de vainilla y manzana para salir de fiesta.",
    stock: true,
    prices: { "5ml": 20000, "10ml": 36000, "full": 210000 },
    notes: { salida: "Manzana, Canela", corazon: "Flor de azahar", fondo: "Vainilla, Haba tonka" }
  },
  {
    id: "supremacy-collector",
    name: "Supremacy Collector Edition",
    brand: "Afnan",
    category: "arabe",
    gender: "hombre",
    img: "assets/SupremacyCollector.png",
    desc: "Intenso, afrutado y ahumado. Proyección bestial y lluvia de cumplidos.",
    stock: true,
    prices: { "5ml": 25000, "10ml": 45000, "full": 270000 },
    notes: { salida: "Grosellas, Bergamota", corazon: "Pachulí, Abedul", fondo: "Almizcle, Musgo" }
  },
  {
    id: "eclaire",
    name: "Eclaire",
    brand: "Lattafa",
    category: "arabe",
    gender: "mujer",
    img: "assets/EclaireLattafa.png",
    desc: "Gourmand irresistible con notas dulces. Una delicia exquisita que enamora.",
    stock: true,
    prices: { "5ml": 20000, "10ml": 38000, "full": 210000 },
    notes: { salida: "Caramelo, leche", corazon: "Miel, flores blancas", fondo: "Vainilla, praliné" }
  },
  {
    id: "liquid-brun",
    name: "Liquid Brun",
    brand: "Lattafa",
    category: "arabe",
    gender: "unisex",
    img: "assets/LiquidBrun.png",
    desc: "Cálido, especiado y sumamente reconfortante. Pura elegancia embotellada.",
    stock: true,
    prices: { "5ml": 25000, "10ml": 44000, "full": 270000 },
    notes: { salida: "Cardamomo, canela", corazon: "Praliné, maderas", fondo: "Vainilla, ámbar" }
  },
  {
    id: "khamrah-qahwa",
    name: "Khamrah Qahwa",
    brand: "Lattafa",
    category: "arabe",
    gender: "unisex",
    img: "assets/KhamrahQahwa.png",
    desc: "El encanto dulce y especiado con un adictivo toque de café tostado.",
    stock: true,
    prices: { "5ml": 22000, "10ml": 38000, "full": 210000 },
    notes: { salida: "Canela, cardamomo", corazon: "Café, praliné", fondo: "Vainilla, haba tonka" }
  },
  {
    id: "sublime",
    name: "Sublime",
    brand: "Lattafa",
    category: "arabe",
    gender: "mujer",
    img: "assets/Sublime.png",
    desc: "Dulce, frutal y juguetón. Una explosión de manzana roja y flores.",
    stock: true,
    prices: { "5ml": 20000, "10ml": 36000, "full": 200000 },
    notes: { salida: "Manzana, lichi", corazon: "Ciruela, rosa", fondo: "Vainilla, musgo" }
  },
  {
    id: "mandarin-sky-elixir",
    name: "Mandarin Sky Elixir",
    brand: "Armaf",
    category: "arabe",
    gender: "hombre",
    img: "assets/MandarinSkyElixir.png",
    desc: "Versión más intensa y profunda del clásico Mandarin Sky. Brillante y ambarado.",
    stock: true,
    prices: { "5ml": 25000, "10ml": 43000, "full": 265000 },
    notes: { salida: "Mandarina, naranja dulce", corazon: "Azafrán, maderas", fondo: "Ámbar, almizcle" }
  },
  {
    id: "odyssey-homme-white",
    name: "Odyssey HOMME White",
    brand: "Armaf",
    category: "arabe",
    gender: "hombre",
    img: "assets/odysseywhite.png",
    desc: "Un perfume infravalorado que sorprende desde el primer spray. Abre fresco y jugoso con cítricos y pimienta rosa, luego evoluciona a un corazón elegante con hojas de violeta y notas marinas. En el fondo, el ámbar y el amberwood crean una estela suave, ligeramente dulce y muy adictiva.",
    stock: true,
    prices: { "5ml": 22000, "10ml": 42000, "full": 220000 },
    notes: { salida: "Pimienta Rosa, Toronja", corazon: "Hojas de violeta, notas marinas", fondo: "Ámbar, Amberwood" }
  },
  {
    id: "hawas-fire",
    name: "Hawas Fire",
    brand: "Rasasi",
    category: "arabe",
    gender: "hombre",
    img: "assets/HawasFire.png",
    desc: "Intenso, especiado y audaz. Una versión ardiente del clásico.",
    stock: true,
    prices: { "5ml": 25000, "10ml": 43000, "full": 270000 },
    notes: { salida: "Especias, pimienta", corazon: "Oud, incienso", fondo: "Ámbar, vetiver" }
  },
  {
    id: "hawas-diva",
    name: "Hawas Diva",
    brand: "Rasasi",
    category: "arabe",
    gender: "mujer",
    img: "assets/HawasDiva.png",
    desc: "Sofisticado, floral y con carácter. Ideal para ella.",
    stock: true,
    prices: { "5ml": 22000, "10ml": 39000, "full": 248000 },
    notes: { salida: "Frutas rojas, bergamota", corazon: "Rosa, jazmín", fondo: "Sándalo, almizcle" }
  },
  {
    id: "asad-bourbon",
    name: "Asad Bourbon",
    brand: "Lattafa",
    category: "arabe",
    gender: "hombre",
    img: "assets/AsadBourbon.png",
    desc: "Dulce, especiado y elegante. Ideal para la noche.",
    stock: true,
    prices: { "5ml": 20000, "10ml": 38000, "full": 210000 },
    notes: { salida: "Pimienta negra, piña", corazon: "Vainilla, café", fondo: "Ámbar, maderas" }
  },
  {
    id: "art-of-universe",
    name: "Art Of Universe",
    brand: "Lattafa",
    category: "arabe",
    gender: "unisex",
    img: "assets/ArtOfUniverse.png",
    desc: "Sofisticado y versátil, con un aire moderno.",
    stock: true,
    prices: { "5ml": 25000, "10ml": 42000, "full": 260000 },
    notes: { salida: "Bergamota, cítricos", corazon: "Notas florales", fondo: "Maderas, almizcle" }
  },
  {
    id: "mandarin-sky",
    name: "Mandarin Sky",
    brand: "Armaf",
    category: "arabe",
    gender: "hombre",
    img: "assets/MandarinSky.png",
    desc: "Cítrico vibrante con corazón cálido. Energizante y optimista.",
    stock: true,
    prices: { "5ml": 20000, "10ml": 36000, "full": 204000 },
    notes: { salida: "Mandarina, bergamota", corazon: "Neroli, flores blancas", fondo: "Cedro, almizcle suave" }
  },
  {
    id: "cdn-urban-man-elixir",
    name: "Club De Nuit Urban Man Elixir",
    brand: "Armaf",
    category: "arabe",
    gender: "hombre",
    img: "assets/cdnUrbanManElixir.png",
    desc: "Fragancia masculina ambarina especiada lanzada en 2022. Salida fresca y especiada que evoluciona a un fondo cálido y amaderado.",
    stock: true,
    isNew: true,
    prices: { "5ml": 25000, "10ml": 42000, "full": 249000 },
    notes: { salida: "Bergamota, Pimienta Rosa, Jazmín, Flor de Azahar del Naranjo", corazon: "Lavanda, Elemí, Geranio, Vetiver, Azafrán, Cempasúchil", fondo: "Ambroxan, Ámbar, Cedro, Pachulí, Ládano" }
  },
  {
    id: "hawas-malibu",
    name: "Hawas Malibú",
    brand: "Rasasi",
    category: "arabe",
    gender: "hombre",
    img: "assets/HawasMalibu.png",
    desc: "Frescura brillante tropical con un toque dulce menos pesado que otros perfumes del estilo. Alta duración, de 8 a 12 horas.",
    stock: true,
    isNew: true,
    prices: { "5ml": 25000, "10ml": 43000, "full": 269000 },
    notes: { salida: "Piña, Naranja, Toronja", corazon: "Ámbar, Raíz de Lirio, Lavanda", fondo: "Haba Tonka, Almizcle, Pachulí, Cachemira" }
  },
  {
    id: "odyssey-mega",
    name: "Odyssey Mega",
    brand: "Armaf",
    category: "arabe",
    gender: "hombre",
    img: "assets/OdysseyMega.png",
    desc: "Amaderado aromático vibrante. Una salida cítrica y especiada que evoluciona hacia un fondo cálido de maderas y almizcle.",
    stock: true,
    isNew: true,
    prices: { "5ml": 20000, "10ml": 35000, "full": 200000 },
    notes: { salida: "Limón, Naranja, Bergamota, Jengibre, Menta", corazon: "Piña, Salvia, Enebro, Geranio", fondo: "Almizcle, Cedro, Haba Tonka, Vetiver" }
  },
  {
    id: "amber-oud-aqua-dubai",
    name: "Amber Oud Aqua Dubai",
    brand: "Al Haramain",
    category: "arabe",
    gender: "unisex",
    img: "assets/AquaDubai.png",
    desc: "Fresco, cítrico y afrutado con un fondo amaderado envolvente. Una fragancia versátil, ideal para el día a día.",
    stock: true,
    isNew: true,
    prices: { "5ml": 25000, "10ml": 42000, "full": 295000 },
    notes: { salida: "Notas verdes, Bergamota, Mandarina", corazon: "Melón, Ámbar, Grosella Negra, Piña", fondo: "Almizcle, Petitgrain, Gálbano, Vainilla" }
  }
];
